apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Blue-Green Demo</title>
    </head>
    <body>
      <h1>Hello from the BLUE version!</h1>
    </body>
    </html>
