apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
    version: blue  # Switch to 'green' to route traffic to green deployment
  ports:
  - port: 80
    targetPort: 80
